CREATE TABLE coffee (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255),
    size VARCHAR(255),
    price INT,
    description VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS userInfo (
    userId BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL
);




